paths:
  train_txt: "./data/charades_sta/charades_sta_train.txt"
  test_txt: "./data/charades_sta/charades_sta_test.txt"
  feat_dir_32f: "./features/clip_features_32f_db"
  feat_dir_64f: "./features/clip_features_64f_db"
  feat_dir_patches_32f: "./features/clip_patches_32f_db"
  feat_dir_anet: "./features/activitynet/vid_clip"
  model_lke_assoc: "./checkpoints/best_charades_sta_lke_assoc_model.pt"
  model_lke: "./checkpoints/best_charades_sta_lke_model.pt"
  save_dir: "./checkpoints"
  charades_v1_train: "./data/charades_sta/Charades_v1_train.csv"
  charades_v1_test: "./data/charades_sta/Charades_v1_test.csv"
  anet_train_json: "./data/activitynet/train.json"
  anet_val1_json: "./data/activitynet/val_1.json"
  anet_val2_json: "./data/activitynet/val_2.json"
  msrvtt_video_dir: "./features/msrvtt/video_features_db"
  msrvtt_text_dir: "./features/msrvtt/text_features_db"
